---

# common
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - common

# web
- hosts: web
  become: yes
  vars:
    web_title: "Ansible Demo"
  roles:
    - web

# lb
- hosts: lb
  become: yes
  roles:
    - lb
